### PR TITLE
WIP: widget rework

### PR DESCRIPTION
**Pull request by Punzo**
This is still in WIP.

### CODE REVIEW

**Comment by Punzo** [comment]
current To Do vtkContourWidget:
- []  add axis constrain
- []  add select and highlight of line
- []  add centroid point
- []  add possiblity of always close the spline
- []  add the possibility to add multiple representations
- [] point, line and angle should be child classes of this or of another middle class

**Comment by Punzo** [comment]
Rework Progress with https://github.com/ProxSim/VTK/commit/173bb46f492c0d250d2357c1ee4f341e5718d8bf:

- [x]  Points -> vtkContourPointsWidget and vtkContourPointsRepresentation

- [x]  Line -> vtkContourLineWidget and vtkContourLineRepresentation

- [x]  Angle -> vtkContourAngleWidget and vtkContourAngleRepresentation

- [x] Open/Closed spline -> vtkContourCurveWidget and vtkContourCurveRepresentation

vtkContourXRepresentation are child classes of vtkContourRepresentation (In addition: probably is worth to move few common methods between all the  vtkContourXRepresentation in the vtkContourRepresentation to get smaller classes, but the idea is to keep at minimum the changes of the original VTK classes)

**Comment by Punzo** [comment]
Hi @lassoan . I finished, You were right without handles widgets everything goes much smoother. In addition, retrieving the point coordinates is very fast because the vtkContourRepresentation uses tree optimization.

There is still some copy and paste between the widget and representation classes.  Shall I add two other intermediate classes: 1) one between vtkContourXRepresentation and vtkContourRepresentation; 2) another between vtkContourXWidget and vtkAbstractWidget ???

Also I am not sure of keeping the Contour in the name, but the issue is that there are already other classes (with the old infra) like vtkCurveRepresentation. So I would like to maintain a prefix, do you have any idea for a better prefix name instead of Contour?

**Comment by Punzo** [comment]
Here videos to show how the widgets look like and what type of interaction is possible to do.

https://www.dropbox.com/s/myvp3gl37pfzeue/closedcurve.mkv?dl=0
https://www.dropbox.com/s/252oepojenkasqb/openCurve.mkv?dl=0
https://www.dropbox.com/s/dn43u7zmr9z86da/Points.mkv?dl=0
https://www.dropbox.com/s/3veiy7bqtngelff/Line.mkv?dl=0
https://www.dropbox.com/s/gthildpv2lrlkup/Angle.mkv?dl=0

A question for @jdx-john: I was thinking that It may be useful as well an option to rotate the widget respect to the centroid, something like shift+left click and drag. I haven't implemented this, but I can add it relatively easy.

**Comment by jdx-john** [comment]
Many thanks for these, very helpful. Some quick queries as I watch... not actually sure if I should do them here or in our repo issue :)

*Closed curve*
- I notice when you click to place a point, the spline gets very 'sharp' angle. Is that because now you have two points in same place (dropped point and cursor) It's slightly annoying though I have no idea how you would do it differently!
- In scaling you scale around centroid, is this calculated same way as in CPA (@Sunderlandkyl did a couple of different centroid implementations based on customer requests)? Centroid calculation might be something other users want to do differently so I don't know if it should be a built-in feature, a separate point-annotation, if it should allow pluggable calculation, or we just do our preference and wait for comments at integration.
- Obviously you don't render centroid yet.

*Open Curve*
- Automatically closing the curve is _not_ preferred in CPA though of course I can see it's a nice feature for VTK/slicer to have it as long as we can disable in our app

*Angle*
- The angle arc can presumably be made optional, and/or we can configure its radius, etc? One idea _might_ be that when the widget is selected/active/hover-over the arc is visible and colored in, when de-selected the arc and number value disappear.

*Misc*
- Is plane widget part of this or totally separate? We don't currently use that but you mentioned it when we spoke recently, maybe it's a pre-existing widget that doesn't need rework?
- I assume if we don't want translate and scale options in CPA we can disable them? They _might_ be useful but initially I'd rather keep featureset identical where possible, and see if they want them after
- keyboard shortcuts might conflict with application ones (and for instance we might want to constrain motion relative to other slices, not view x/y)


>A question for @jdx-john: I was thinking that It may be useful as well an option to rotate the widget respect to the centroid, something like shift+left click and drag. I haven't implemented this, but I can add it relatively easy.

Is this just for closed curve? I don't _think_ it is useful for CPA because in all cases the points are mapped to anatomy and are hand-placed carefully, but if it's easy to add in VTK I don't mind that if you consider it useful to Slicer? I would probably say that it makes sense in two cases:
1. Rotating closed curve around centroid
2. Rotating angle about it's center point

It's looking really good @Punzo

**Comment by lassoan** [comment]
Thank you @Punzo these look great! Scaling, etc. will be useful in general (so don't remove them) but most probably can be disabled for most annotations in CPA.

> Also I am not sure of keeping the Contour in the name

Integration of the widgets into Slicer will be much easier and operation will be much faster if we don't try to keep the widgets very generic (VTK-only) but freely make Slicer-specific modifications as we see fit.

Widget class names will contain "Slicer" (vtkSlicerCurveRepresentation), so there will be no name clash.

There will be huge advantages in using Slicer-specific mechanisms, as it will be much easier to implement conversion between slice and 3D coordinate system, transformation using transform nodes, setting display properties by directly getting from display nodes, synchronizing properties between multiple views, etc. Software integration is easier, too, if we only need to add/modify classes in Slicer. In the long term, VTK developers could learn from what we did and could add Slicer-independent versions of these widgets to VTK.

> There is still some copy and paste between the widget and representation classes. Shall I add two other intermediate classes

Using Slicer-specific classes (at the abstract widget level, too) should solve this, too.

What do you think about moving all these classes to Proxsim/Slicer repository (Modules/Loadable/Markups/VTKWidgets) and continue the work there?

Integration is should be much easier if everything is in one repository. If you agree, then please move the code and I will add detailed comments there.

**Comment by Punzo** [comment]
@lassoan I agree in moving the classes into Slicer. I'll add the SlicerAbstract intermediate classes (to clean some copy and paste) and then I'll move everything to Modules/Loadable/Markups/VTKWidgets. 
I'll notify you when it is ready for review. 

We still need some very few modifications (few lines) of this PR at VTK level.

**Comment by Punzo** [comment]
@jdx-john, here is fine due are feedback specific to the VTK implementation.

1) Closed curve: 
A) yeah that is because of the interpolation used, I am not sure we can avoid it, but I'll look at it.
B) I'll check how the centroid is calculated in CPA.
C) you are right, I simply forgot. Thanks for the reminder

2) Open Curve: Ok I'll make it optional

3) yes, it can be already completly configurable

4) A) The plane widget is already implemented and Slicer uses it. i.e., when putting a Slice on the 3D view, we can also enable the plane widget to move or orient the slice directly from the 3D view.
B) they can be disabled.
C) Ok, these are hard-coded, I can make them configurable as well. Constrain along a slice view (i.e., pleane) is not possible now, but it can be implemented, if desired. 

>Is this just for closed curve? I don't think it is useful for CPA because in all cases the points are mapped to anatomy and are hand-placed carefully, but if it's easy to add in VTK I don't mind that if you consider it useful to Slicer? I would probably say that it makes sense in two cases:
Rotating closed curve around centroid
Rotating angle about it's center point

I was thinking the same cases. Then I'll add it

**Comment by cpinter** [comment]
I hope you don't mind me chiming in despite the fact that this is the first time I see these widgets in action:

1/A) We don't see your clicks in the videos, so I'm not sure what you do to place a new point. But the sharp curve appears becasue the new point is very close to another point. If you place a new point near its final position then all this won't occur I guess. What's the reason the new points always seem to appear right next to existing ones?

**Comment by Punzo** [comment]
> I hope you don't mind me chiming in despite the fact that this is the first time I see these widgets in action

no problem at all, the opposite (: . 


> We don't see your clicks in the videos, so I'm not sure what you do to place a new point. 

with left click (P.S.: in the videos, there is also the audio, in which I explain things)    

> But the sharp curve appears becasue the new point is very close to another point.

yes indeed.

>  If you place a new point near its final position then all this won't occur I guess. What's the reason the new points always seem to appear right next to existing ones?

Simply, as soon as you place a point, a second one will be placed in the same position, then as the mouse move the second point position will be updated with the mouse coordinates. In this way you can have already a preview how the interpolated closed curve will appear, before placing "definitively" the new point (P.S.: this option of point place preview is actually optional, it can be disabled).

**Comment by jdx-john** [comment]
Makes sense. I don't know which CPA prefers though probably mirror close to existing functionality if it can be toggled.

One other note for CPA is we don't (shouldn't anyway) allow closed splines with <3 points. Kind of low priority as in practice nobody would try

**Comment by Punzo** [comment]
> One other note for CPA is we don't (shouldn't anyway) allow closed splines with <3 points. Kind of low priority as in practice nobody would try

ok I'll put an additional check that the minimum number of points has to be 3

**Comment by Punzo** [comment]
In commit https://github.com/ProxSim/VTK/pull/5/commits/29393f60d242f6fea661b7b42d043e5d117d7ab6 I have implemented the various comments (visibility of the centroid, make several things optional, cleaning the classes by additional abstract classes, etc...). 

Tomorrow I'll start to integrate them in Slicer (by moving them directly to Slicer).

I have only one question (@jdx-john @Sunderlandkyl ) regarding point 1B: the calculation of the position of the centroid. @jdx-john  said that in CPA should be calculated in a particular way. For what I see in https://github.com/ProxSim/cpa/blob/12e97c4b89d6feee3e6d95606d8cba20b1ffc741/Modules/Scripted/CpaMain/CpaLib/Annotation.py#L885-L896, the centroid in CPA is calculated as the mean of an oversampled line. Why is not simply the mean of the "real" points? Are the results different of a big epsilon (i.e. > half of a pixel)? 

Update: ok I have just seen that the sampling for the calculation of the centroid has a constant step distance (I thought it was constant number of intermediates points). Therefore, in some cases the results will be largely different. @jdx-john do you want that I implement the calculation of the centroid as in https://github.com/ProxSim/cpa/blob/12e97c4b89d6feee3e6d95606d8cba20b1ffc741/Modules/Scripted/CpaMain/CpaLib/Annotation.py#L885-L896 for the widgets?

**Comment by Sunderlandkyl** [comment]
I believe that the idea was that the centroid should be the centre of the curve, not the centre of the placed points, hence the sampling of the line.

**Comment by Punzo** [comment]
> I believe that the idea was that the centroid should be the centre of the curve, not the centre of the placed points, hence the sampling of the line.

ok, perfect, thanks.

**Comment by jdx-john** [comment]
Exactly. If you drew a circle with points closely spaced on one side and only a few on the other, the centroid wasn't the center of the circle and it should be.

I could see an argument for both to be valid in different cases but VTK/Slicer didn't sort this feature before so it's not like we're breaking anything just implementing our solution... If someone else wants a different calculation they can add it

**Comment by lassoan** [comment]
Centroid of resampled points should work well (difficult to imagine a case when you want to determine centroid based on control point locations and not based on curve points).

I'm really looking forward to seeing the Slicer integration started. There is great interest and readily available developers to implement various features if we get a basic framework working in Slicer. See discussion https://discourse.slicer.org/t/2018-12-04-hangout/4949/12#.

**Comment by Punzo** [comment]
> Centroid of resampled points should work well (difficult to imagine a case when you want to determine centroid based on control point locations and not based on curve points).

ok, perfect.

> I'm really looking forward to seeing the Slicer integration started. There is great interest and readily available developers to implement various features if we get a basic framework working in Slicer. See discussion https://discourse.slicer.org/t/2018-12-04-hangout/4949/12#.

yeap starting now. That's good, I will also add a reply to the thread adding few more info and the video that I posted here. I think it will be good if we get already some preliminary feedback.

**Comment by lassoan** [comment]
@Punzo I would like to work on the custom widgets and if they are stable enough then integrate them into the Slicer core during the project week (Jan 28-Feb 1). However, for this, it would be important to minimize the required VTK changes. Since we won't use seed widget anymore, etc. some of the earlier fixes and optimizations may become unnecessary and so we can remove those, and maybe we can also let go some of the other changes that just make things a bit nicer (such as most changes in this pull request).

Could you prepare a VTK branch that only contains essential changes?
(it is fine to do any customization or changes in Slicer core instead)

Do you think the widgets (at least markup points features) could be ready to be merged to Slicer core around Jan 28?

**Comment by Punzo** [comment]
> Could you prepare a VTK branch that only contains essential changes?
(it is fine to do any customization or changes in Slicer core instead)

ok, I can do that

> Do you think the widgets (at least markup points features) could be ready to be merged to Slicer core around Jan 28?

yes definitely. I plan to finish the fiducials soon. See https://github.com/ProxSim/Slicer/pull/16#issuecomment-452726694

**Comment by lassoan** [comment]
@Punzo When do you think the code is ready for public review and testing? If it is then please push the changes to your own public Slicer/VTK fork and let me know and I'll start testing and share it with others.

**Comment by Punzo** [comment]
> @Punzo When do you think the code is ready for public review and testing? If it is then please push the changes to your own public Slicer/VTK fork and let me know and I'll start testing and share it with others.

I think few others days (~2/3) I will finish the fiducials (points widget), i.e. finishing point 2 and 3 in https://github.com/ProxSim/Slicer/pull/16#issuecomment-448690669. I'll update you soon.

**Comment by Punzo** [comment]
moved to https://github.com/Slicer/VTK/pull/20

**Pull request closed without merging**
